version: '3'

services:
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8088:8080
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakpassword
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3308:3306

networks:
  default:
    external: true
    name: keycloakmysql
